### ISSUE TITLE
image

### ISSUE THREAD

**Issue by glepnir** [glepnir/zephyr-nvim#1]
![zephyr](https://user-images.githubusercontent.com/41671631/95203442-577bd200-0815-11eb-9cf9-47f5c5d1b15f.png)

**Comment by glepnir** [comment]
![Uploading zephyr.png…]()

**Comment by glepnir** [comment]
![zephyr](https://user-images.githubusercontent.com/41671631/97680910-667f3880-1ad2-11eb-9cc9-0d8fb8320d07.png)

**Comment by glepnir** [comment]
![zephyr2 0](https://user-images.githubusercontent.com/41671631/97704427-56288700-1aed-11eb-88fc-c26bdc0397f4.png)

**Comment by glepnir** [comment]
![zephyr2 0](https://user-images.githubusercontent.com/41671631/109389317-0cd72f80-7947-11eb-85ba-1f080c64550c.png)

**Comment by glepnir** [comment]
![version 3 0](https://user-images.githubusercontent.com/41671631/109469853-9141c380-7aa9-11eb-9a52-4d9a210b898e.png)

**Comment by glepnir** [comment]
![zephyr3 1](https://user-images.githubusercontent.com/41671631/110074247-d886c780-7dbb-11eb-8d86-a7458a0ca588.png)

**Comment by glepnir** [comment]
![zephyr](https://user-images.githubusercontent.com/41671631/110207650-e291ee80-7ebf-11eb-813d-305fee299322.png)

**Comment by glepnir** [comment]
![QQ20220530-205612](https://user-images.githubusercontent.com/41671631/170997163-650c7ada-fb4f-4c2b-9e17-3398b271a575.png)

**Comment by glepnir** [comment]
![QQ20220605-185145](https://user-images.githubusercontent.com/41671631/172047114-58deb5a9-f67b-400b-bace-2982bf901ff6.png)

**Comment by subnut** [comment]
What font is this?

<sup>Looks nice...</sup>
