### ISSUE TITLE
Change Directory foreground color

### ISSUE THREAD

**Issue by huyvohcmc** [glepnir/zephyr-nvim#12]
Currently when using vim-dirvish with zephyr, the folders are nearly unseenable:
<img width="490" alt="Screen Shot 2021-04-07 at 12 52 58 AM" src="https://user-images.githubusercontent.com/17645203/113756464-9abeeb00-973b-11eb-847e-00eb544802e9.png">
I suggest that we change Directory's fg to cyan or something:
```
Directory = {fg=zephyr.cyan,bg=zephyr.none};
```

**Comment by jack828** [comment]
Buffer tabs are also very hard to read, active or not 
![image](https://user-images.githubusercontent.com/6363719/113845916-e4d0bc80-978d-11eb-91f1-1bbc1760a5bd.png)

**Comment by Shatur** [comment]
Not sure if it's related, but filenames in Quickfix also look weird:
![изображение](https://user-images.githubusercontent.com/22453358/114053727-e1c1f300-9897-11eb-9c80-43da8a424e60.png)

**Comment by Shatur** [comment]
The issue was fixed by 9667a24b5cf9f2f6675f015c04402cf94f5bffd8.

**Comment by glepnir** [comment]
now closed. fix
