### ISSUE TITLE
commit 32c4ea9 makes everything blue....

### ISSUE THREAD

**Issue by tzachar** [glepnir/zephyr-nvim#16]
After 32c4ea9, I get a blue screen....
b4:
![Screenshot from 2021-04-22 10-15-55](https://user-images.githubusercontent.com/4946827/115671979-c05f0d80-a353-11eb-94a9-31a2881b6fc5.png)
after:
![Screenshot from 2021-04-22 10-14-24](https://user-images.githubusercontent.com/4946827/115671995-c48b2b00-a353-11eb-965d-ebb2a75dd2fb.png)

**Comment by glepnir** [comment]
@tzachar  which language do you write ?

**Comment by tzachar** [comment]
Mostly python

**Comment by glepnir** [comment]
because the new feature is tsvariable highlight. check your image..it's wried i don't config the light yellow color in zephyr.

**Comment by tzachar** [comment]
The light yellow is my default foreground:
```vim
highlight Normal guibg=black guifg=wheat    
```

Right now, I am indeed disabling the TSVariable settings you added. However, it would be nice to be able to override the default settings.

**Comment by LimbicSys** [comment]
How to override the `TSVariable` highlight?  I try to set  the command `hi TSVariable guifg=xx` as an auto command after `ColorScheme` or `VimEnter` event. But  it does not work.

**Comment by tzachar** [comment]
Check out PR #17
