### ISSUE TITLE
Treesitter highlight error : invalid node type at position 4756

### ISSUE THREAD

**Issue by krisfans** [glepnir/zephyr-nvim#29]
## Repetition steps
1. put `glepnir/zephyr-nvim` and `nvim-treesitter/nvim-treesitter` into `~/.local/share/nvim/site/pack/foo/start`
2. nvim -u mini.vim mini.vim
## mini.vim
```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" " set runtimepath+=~/.cache/nvim/dein/repos/github.com/nvim-treesitter/nvim-treesitter
" " set runtimepath+=~/.cache/nvim/dein/repos/github.com/glepnir/zephyr-nvim
" set runtimepath+=~/.cache/nvim/dein/repos/github.com/Shougo/dein.vim
" let g:dein#auto_recache = 1
" " Required:
" if dein#load_state('$HOME/.cache/nvim/dein/')
"   call dein#begin('$HOME/.cache/nvim/dein/')
"   " Let dein manage dein
"   " Required:
"   call dein#add('Shougo/dein.vim')
"   call dein#add('nvim-treesitter/nvim-treesitter')
"   call dein#add('glepnir/zephyr-nvim')
"   " Required:
"   call dein#end()
"   call dein#save_state()
" endif

" call dein#call_hook('source')
" call dein#call_hook('post_source')

filetype plugin indent on
syntax enable
set termguicolors

lua << EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = "all", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
    ignore_install = { "glsl" }, -- List of parsers to ignore installing
    highlight = {
        enable = true,              -- false will disable the whole extension
        -- disable = { "glsl", "latex" },  -- list of language that will be disabled EOF
        additional_vim_regex_highlighting = false,
    },
    indent = {
        enable = true
    }
}
EOF

colorscheme zephyr
```

## Error: 
-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 4756
![QQ截图20220125221617](https://user-images.githubusercontent.com/57793534/150994481-37823d25-f1fd-47e5-9839-f9251614b6a5.png)

**Comment by fcnaud** [comment]
可以看下这里，https://github.com/nvim-treesitter/nvim-treesitter/issues/2519

我也遇到了这个情况，大概就是这个主题和 treesitter 有冲突，你把这个项目 fork 一份，把这个文件[after/queries/lua/highlights.scm](https://github.com/glepnir/zephyr-nvim/blob/32c4ea97cc1cd3db1abebd46aff2ee18d66d8d59/after/queries/lua/highlights.scm) 删了，然后用你 fork 的项目，应该就没问题了

**Comment by 0xjairo** [comment]
@fcnaud 's reply in English (from Google Translate):
> You can look here, nvim-treesitter/nvim-treesitter#2519
>
> I also encountered this situation, probably because this theme conflicts with treesitter, you fork this project, delete this file after/queries/lua/highlights.scm, and then use your fork project, it should be fine span

**Comment by LuYanFCP** [comment]
@krisfans  you could modify highlights.scm to https://github.com/glepnir/zephyr-nvim/pull/30/files

**Comment by glepnir** [comment]
should be work now.
