### ISSUE TITLE
Could you make this colorscheme toggleable?

### ISSUE THREAD

**Issue by nyngwang** [glepnir/zephyr-nvim#37]
I cannot change back to this colorscheme from another one.

---

If I call `require('zephyr').colorscheme()` directly I got a different colorscheme:

<img src="https://user-images.githubusercontent.com/24765272/206024313-841055c6-3fce-4136-b7f7-b70a83cd0555.png" width="500">

than the default one:

<img src="https://user-images.githubusercontent.com/24765272/206024564-388552ca-3618-4a2d-bda2-80c3fd95d9f0.png" width="500">

**Comment by chrisgrieser** [comment]
I also have this issue, the colorscheme can only be set once. changing to a different colorscheme and back does work.

This is also relevant when using plugins like [styler](https://github.com/folke/styler.nvim) or [autodarkmode](https://github.com/f-person/auto-dark-mode.nvim).

I had the same issue with oxocarbon, maybe you can take a look how they solved it? https://github.com/nyoom-engineering/oxocarbon.nvim/issues/38

**Comment by nyngwang** [comment]
Hi @chrisgrieser! Thanks and closing...

**Comment by chrisgrieser** [comment]
@nyngwang wait, why are you closing it when the issue has not been solved?
