### ISSUE TITLE
Highlighting for new lsp diagnostic

### ISSUE THREAD

**Issue by carlitux** [glepnir/zephyr-nvim#4]
New diagnostic from lsp-handlers has new Highlights, any plan to include them.

Thanks for this colorscheme, I love it.

**Comment by glepnir** [comment]
Already support，but i forget commit…when i wake up . I will update

**Comment by glepnir** [comment]
update.

**Comment by carlitux** [comment]
just another question, underline is also supported?

**Comment by glepnir** [comment]
How about now?

**Comment by carlitux** [comment]
thank you! 

it looks really great.
